BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_DIR   = ~/Downloads/arduino-1.8.3/
ARDUINO_LIBS = CmdMessenger


include /usr/share/arduino/Arduino.mk


# ARDMK_DIR     = /usr/share/arduino/Arduino.mk
# AVR_TOOLS_DIR = /usr
# MONITOR_PORT  = /dev/ttyACM0
# BOARD_TAG     = mega2560

# ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
# ARDMK_DIR     = /usr/local
# AVR_TOOLS_DIR = /usr
# MONITOR_PORT  = /dev/ttyACM0
# BOARD_TAG     = mega2560
